# Generated by Django 4.2.30 on 2026-10-09 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battles", "0002_battle_invited"),
    ]

    operations = [
        migrations.AlterField(
            model_name="battle",
            name="mode",
            field=models.CharField(
                choices=[
                    ("ranked", "ranked"),
                    ("friendly", "friendly"),
                    ("practice", "practice"),
                    ("ffa", "ffa"),
                    ("team", "team"),
                    ("boss", "boss"),
                ],
                max_length=10,
            ),
        ),
    ]
