# Generated by Django 4.2.30 on 2026-10-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_item", models.CharField(max_length=40)),
                ("source_layer", models.IntegerField()),
                ("source_object_id", models.CharField(max_length=40)),
                ("name", models.CharField(max_length=300)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("castle", "castle"),
                            ("lookout", "lookout"),
                            ("spring", "spring"),
                            ("culture", "culture"),
                            ("nature", "nature"),
                            ("heritage", "heritage"),
                            ("food", "food"),
                            ("info", "info"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("subtype", models.CharField(blank=True, max_length=100)),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("description", models.TextField(blank=True)),
                ("url", models.URLField(blank=True, max_length=500)),
                ("obec_kod", models.CharField(blank=True, max_length=10)),
                ("obec", models.CharField(blank=True, max_length=100)),
                ("okres", models.CharField(blank=True, db_index=True, max_length=100)),
                ("orp", models.CharField(blank=True, max_length=100)),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("common", "common"),
                            ("rare", "rare"),
                            ("epic", "epic"),
                            ("legendary", "legendary"),
                        ],
                        default="common",
                        max_length=12,
                    ),
                ),
                ("is_hazardous", models.BooleanField(default=False)),
                ("nearest_stop_name", models.CharField(blank=True, max_length=200)),
                ("nearest_stop_m", models.IntegerField(blank=True, null=True)),
                ("license", models.CharField(default="CC0", max_length=50)),
                ("source_url", models.URLField(blank=True, max_length=500)),
                ("extra", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["lat", "lon"], name="places_plac_lat_d1ae26_idx"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="place",
            constraint=models.UniqueConstraint(
                fields=("source_item", "source_layer", "source_object_id"),
                name="uniq_place_source",
            ),
        ),
    ]
