# Generated by Django 4.2.30 on 2026-10-09 17:22

import apps.game.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("places", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=40, unique=True)),
                ("name", models.CharField(max_length=80)),
                ("description", models.CharField(max_length=300)),
                ("rule", models.JSONField()),
                ("icon", models.CharField(default="🏅", max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name="CheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("accuracy_m", models.FloatField()),
                ("distance_m", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        storage=apps.game.models.private_storage,
                        upload_to="checkins/%Y/%m/",
                    ),
                ),
                (
                    "photo_sha256",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("photo_phash", models.CharField(blank=True, max_length=16)),
                ("exif_status", models.CharField(default="missing", max_length=10)),
                ("trust", models.IntegerField(default=100)),
                ("verified", models.BooleanField(default=False)),
                ("is_demo", models.BooleanField(default=False)),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkins",
                        to="places.place",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("awarded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.badge"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(max_length=30, unique=True)),
                (
                    "age_group",
                    models.CharField(
                        choices=[("under18", "under18"), ("adult", "adult")],
                        default="adult",
                        max_length=10,
                    ),
                ),
                ("consent_confirmed", models.BooleanField(default=False)),
                ("school", models.CharField(blank=True, db_index=True, max_length=120)),
                ("xp", models.IntegerField(default=0)),
                ("level", models.IntegerField(default=1)),
                ("rating", models.IntegerField(default=1000)),
                ("wins", models.IntegerField(default=0)),
                ("photo_public", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("species", models.CharField(max_length=40)),
                ("type", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=40)),
                ("rarity", models.CharField(max_length=12)),
                ("hp", models.IntegerField()),
                ("atk", models.IntegerField()),
                ("defense", models.IntegerField()),
                ("spd", models.IntegerField()),
                ("level", models.IntegerField(default=1)),
                ("xp", models.IntegerField(default=0)),
                ("seed", models.BigIntegerField()),
                ("lore", models.TextField(blank=True)),
                ("verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "checkin",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pet",
                        to="game.checkin",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pets",
                        to="places.place",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="userbadge",
            constraint=models.UniqueConstraint(
                fields=("user", "badge"), name="uniq_user_badge"
            ),
        ),
        migrations.AddConstraint(
            model_name="checkin",
            constraint=models.UniqueConstraint(
                fields=("user", "place"), name="uniq_checkin_user_place"
            ),
        ),
    ]
