# Generated by Django 4.2.30 on 2026-10-09 19:13

from django.db import migrations, models


def backfill(apps, schema_editor):
    """Starší PETi dostanou magii a výdrž ze svého seedu (stejně jako noví) a level podle nové křivky XP."""
    import random
    from apps.game import pets
    for p in apps.get_model('game', 'Pet').objects.all():
        rng = random.Random(p.seed)
        mult = pets.RARITY_MULT.get(p.rarity, 1)
        bias = pets.TYPE_BIAS.get(p.type, {})
        p.mag = round(20 * mult * rng.uniform(0.9, 1.1) * bias.get('mag', 1))
        p.stamina = round(100 * mult * rng.uniform(0.9, 1.1) * bias.get('stamina', 1))
        p.level = pets.level_for_xp(p.xp)
        p.save(update_fields=['mag', 'stamina', 'level'])


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_team_profile_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="injured_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pet",
            name="mag",
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name="pet",
            name="stage",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="pet",
            name="stamina",
            field=models.IntegerField(default=100),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
