# Generated by Django 4.2.30 on 2026-10-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_friendship_friendship_uniq_friendship"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkin",
            name="forgotten",
            field=models.BooleanField(default=False),
        ),
    ]
