# Generated by Django 4.2.30 on 2026-10-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_checkin_forgotten"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="rating",
            field=models.IntegerField(default=0),
        ),
    ]
