# Generated by Django 4.2.30 on 2026-10-09 23:04

from django.conf import settings
from django.db import migrations, models


def backfill_battle_points(apps, schema_editor):
    """Body za dosavadní výhry v 1v1 (dřív se hodnocení počítalo přímo z tabulky soubojů)."""
    points = {'ranked': 30, 'friendly': 15, 'practice': 5}
    Profile = apps.get_model('game', 'Profile')
    for b in apps.get_model('battles', 'Battle').objects.filter(status='finished', winner__in=('a', 'b')):
        uid = b.player_a_id if b.winner == 'a' else b.player_b_id
        if uid:
            Profile.objects.filter(user_id=uid).update(battle_points=models.F('battle_points') + points.get(b.mode, 0))
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("battles", "0002_battle_invited"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("places", "0002_swim_extra"),
        ("game", "0006_profile_rating_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="bonus_move",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="pet",
            name="favorite",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pet",
            name="type2",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="profile",
            name="battle_points",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="pet",
            name="checkin",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pet",
                to="game.checkin",
            ),
        ),
        migrations.CreateModel(
            name="BossWin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boss_wins",
                        to="places.place",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boss_wins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="bosswin",
            constraint=models.UniqueConstraint(
                fields=("user", "place", "day"), name="uniq_boss_win"
            ),
        ),
        migrations.RunPython(backfill_battle_points, migrations.RunPython.noop),
    ]
